// Supported delivery cities — TEMPORARY stopgap until DHL/nationwide courier.
// Keep this list in sync with backend/utils/cityRestriction.js (SUPPORTED_CITIES).
export const SUPPORTED_CITIES = [
  'Alberton',
  'Ballito',
  'Bela-Bela',
  'Bellville',
  'Benoni',
  'Bethlehem',
  'Bloemfontein',
  'Boksburg',
  'Brits',
  'Cape Town',
  'Centurion',
  'Durban',
  'East London',
  'Empangeni',
  'George',
  'Germiston',
  'Gqeberha',
  'Hermanus',
  'Johannesburg',
  'Kempton Park',
  'Kimberley',
  'Klerksdorp',
  'Knysna',
  'Kroonstad',
  'Krugersdorp',
  'Ladysmith',
  'Mahikeng',
  'Margate',
  'Mbombela',
  'Middelburg',
  'Midrand',
  'Mokopane',
  'Mossel Bay',
  'Mthatha',
  'Musina',
  'Newcastle',
  'Oudtshoorn',
  'Paarl',
  'Phuthaditjhaba',
  'Pietermaritzburg',
  'Pinetown',
  'Polokwane',
  'Port Elizabeth',
  'Potchefstroom',
  'Pretoria',
  'Queenstown',
  'Randburg',
  'Richards Bay',
  'Roodepoort',
  'Rustenburg',
  'Sandton',
  'Sasolburg',
  'Secunda',
  'Somerset West',
  'Soweto',
  'Springbok',
  'Springs',
  'Standerton',
  'Stellenbosch',
  'Thohoyandou',
  'Tzaneen',
  'Uitenhage',
  'Umhlanga',
  'Upington',
  'Vanderbijlpark',
  'Vereeniging',
  'Welkom',
  'White River',
  'Witbank',
  'Worcester',
] as const

export type SupportedCity = (typeof SUPPORTED_CITIES)[number]
